# Generated by Django 5.0.7 on 2024-07-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('roadAddress', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=30)),
                ('link', models.URLField(max_length=100)),
                ('description', models.TextField()),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
            ],
        ),
    ]
