# Generated by Django 4.2.14 on 2024-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
