# Generated by Django 5.0.7 on 2024-07-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
