# Generated by Django 4.2.14 on 2024-07-31 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0002_alter_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.ImageField(blank=True, upload_to='image/stamps')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_info.store')),
            ],
        ),
    ]
