# Generated by Django 4.2.14 on 2024-07-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0003_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='stamp',
        ),
        migrations.AddField(
            model_name='stamp',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
