# Generated by Django 5.0.7 on 2024-07-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0003_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
