# Generated by Django 5.0.7 on 2024-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0004_store_id_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
