# Generated by Django 4.2.14 on 2024-07-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_info', '0004_remove_stamp_stamp_stamp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
